development:
 adapter: postgresql
 encoding: unicode
 database: twitterdigi_development
 host: localhost
 pool: 5
 timeout: 5000
 username: 
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: twitterdigi_test
 host: localhost
 pool: 5
 timeout: 5000
 username:
 password:

production:
 adapter: postgresql
 encoding: unicode
 database: twitterdigi_production
 host: localhost
 pool: 5
 timeout: 5000
 username: deploy
 password: Mahendhar9$
